# Generated by Django 4.1.3 on 2022-11-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('role_description', models.CharField(max_length=422)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact_no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_role_id', models.ForeignKey(db_column='user_role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
