# Generated by Django 4.1.3 on 2022-12-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tests_option6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='option6',
        ),
    ]
