# Generated by Django 4.1.3 on 2022-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roles_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=422)),
                ('course_description', models.CharField(max_length=422)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_title',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Teacher'), ('3', 'Student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.CharField(max_length=422)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
            ],
            options={
                'db_table': 'durations',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='course_duration_id',
            field=models.ForeignKey(db_column='course_duration_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.duration'),
        ),
    ]
