# Generated by Django 4.1.3 on 2022-11-11 15:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_courses_code_duration_date_created_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_duration_id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.SlugField(db_column='course_code', default=accounts.models.random_string, max_length=10, unique=True),
        ),
    ]
