# Generated by Django 4.1.3 on 2022-11-14 09:28

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_courses_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_thumbnail',
            field=models.ImageField(null=True, upload_to=accounts.models.filepath),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=422, null=True)),
                ('resource_description', models.CharField(max_length=422, null=True)),
                ('resource', models.FileField(null=True, upload_to=accounts.models.filePdfPath)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
