# Generated by Django 4.1.3 on 2022-11-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_courses_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_description',
            field=models.TextField(null=True),
        ),
    ]
