# Generated by Django 4.1.3 on 2022-11-15 05:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_resources_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=accounts.models.fileUserpath),
        ),
    ]
