# Generated by Django 4.1.3 on 2022-11-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_users_profile_description_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('option1', models.TextField(null=True)),
                ('option2', models.TextField(null=True)),
                ('option3', models.TextField(null=True)),
                ('option4', models.TextField(null=True)),
                ('option5', models.TextField(null=True)),
                ('correct', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4'), ('5', 'Option 5')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
