# Generated by Django 4.1.3 on 2022-11-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='option5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
