# Generated by Django 4.1.3 on 2022-11-15 12:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_users_current_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.fileUserpath),
        ),
    ]
