# Generated by Django 4.1.3 on 2022-11-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_users_profile_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolled',
            new_name='Enrolls',
        ),
        migrations.RenameField(
            model_name='enrolls',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='enrolls',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='enrolls',
            table='enrolls',
        ),
    ]
