# Generated by Django 4.1.3 on 2022-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_enrolled_enrolls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolls',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=422),
        ),
    ]
