# Generated by Django 4.1.3 on 2022-11-17 15:30

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_enrolls_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_amount', models.IntegerField()),
                ('payment_image', models.ImageField(null=True, upload_to=accounts.models.filePaymentPath)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Bank account', 'Bank account')], max_length=100)),
                ('status', models.CharField(choices=[('1', 'true'), ('0', 'false')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
            ],
            options={
                'db_table': 'fees',
            },
        ),
    ]
