# Generated by Django 4.1.3 on 2022-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_feespayment_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
