# Generated by Django 4.1.3 on 2022-11-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_fees_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
