# Generated by Django 4.1.3 on 2022-11-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_fees_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='course_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.courses'),
        ),
    ]
