# Generated by Django 4.1.3 on 2022-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_feespayment_paid_from_feespayment_paid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='is_free',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
