# Generated by Django 4.1.3 on 2022-11-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_fees_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
    ]
