# Generated by Django 4.1.3 on 2022-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_fees_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_description',
            field=models.CharField(blank=True, max_length=422),
        ),
    ]
