# Generated by Django 4.1.3 on 2022-11-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_roles_role_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feespayment',
            old_name='Paid_amount',
            new_name='paid_amount',
        ),
    ]
