# Generated by Django 4.1.3 on 2022-11-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_paid_amount_feespayment_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(blank=True, max_length=100)),
                ('new_password', models.CharField(blank=True, max_length=100)),
                ('retype_password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fees',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
