# Generated by Django 4.1.3 on 2022-11-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_changepassword_alter_fees_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolls',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
    ]
