# Generated by Django 4.1.3 on 2022-11-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_enrolls_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.courses'),
        ),
    ]
