# Generated by Django 4.1.3 on 2022-11-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_duration_course_id_alter_feespayment_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolls',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='paid_from',
            field=models.ForeignKey(db_column='paid_from', on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
        ),
    ]
